# Generated by Django 2.2.7 on 2020-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts1', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
