# Generated by Django 2.2.7 on 2020-02-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts1', '0008_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
